### ISSUE TITLE
Main.snl will not build

### ISSUE THREAD

**Issue by godreborn** [marcussacana/FridayNightFunkin#3]
I'm getting this error: 
![image](https://github.com/user-attachments/assets/57f2febb-bb87-4385-8fdb-ca787d580e59)

I'm much more familiar with building ps4 stuff in linux, but I saw that the Makefile is currently broken for linux, so I'm trying it in vs 2022.  I had to update to .net framework 4.8, since 4.5 is no longer supported.  I also wasn't sure which llvm+clang to use, since I remembered sm64 for ps4 needing clang-10 iirc, so I thought I'd use that.  either way, it fails with the same error.

**Comment by marcussacana** [comment]
Hi, you can't upgrade the .net framework because is the highest version that PS4 support it.
The VS22 can build .net 4.5 projects but with some hacks, check https://stackoverflow.com/a/75651725

**Comment by godreborn** [comment]
> Hi, you can't upgrade the .net framework because is the highest version that PS4 support it. The VS22 can build .net 4.5 projects but with some hacks, check https://stackoverflow.com/a/75651725

thanks.  that worked, but I got a new error (only one this time), with main.snl:

![image](https://github.com/user-attachments/assets/c16a1785-2a5f-4e97-ad0f-65f58817caa2)

since the end result example says "release," I've been building orbisgl and main as "release," with x64 for main.  is that incorrect?

**Comment by godreborn** [comment]
I just now noticed something.  GLTest keeps being skipped by visual studio 2022.  I have no idea why.

**Comment by godreborn** [comment]
okay, I think I got it to work.  I also had to use 0.5.2 of OpenOrbis.  it build an eboot.bin, but it said failed at building main.exe, which I don't understand.  the eboot succeeded though.  however, I thought it was supposed to build a pkg

**Comment by godreborn** [comment]
nm, I figured it out: 
![image](https://github.com/user-attachments/assets/044dbc61-d789-403d-9f90-d0e662b97943)

success.

**Comment by marcussacana** [comment]
GLTest should be built only in Debug builds, I've made the VS ignore it when you try build as release, for some reason seems not worked for you.
You can just right click the project at visual studio "Soluction Explorer" and click at "Unload Project" to prevent the error.
I recommend keep the OrbisGL updated due bug fixes, I don't remember to update the one that this repo is using.

**Comment by godreborn** [comment]
thanks.  I figured that out sorta, because the main repo was trying to create a debug build.  I was able to overcome that error by: Right clicking on the project
Selecting "Properties"
Setting "Output Type" to "Class Library"  it built it after that.  I found the solution elsewhere.  it built the package too with no errors:  
![image](https://github.com/user-attachments/assets/0638a5da-5305-4954-b60a-e4974a8e08df)

unfortunately, I don't have a ps4 to test it, and my ps5 is unhacked.  I kept the build, since it was a bit of trial-and-error, but I think I have it figured out.  thanks for the help.

**Comment by godreborn** [comment]
I also had to use 0.5.2 for OpenOrbis, since 0.5.1 seemed to be missing one of the fself files in bin.

**Comment by godreborn** [comment]
btw, here's the full output of the end of the build.  it required the powershell cmd terminal btw, possibly because of tmp.ps1?  I also had to install .net framework or .net core (forgot which) 3.0 for console application or it error'd about it being missing in powershell terminal in vs 2022.  I'll have to have someone test my build probably at some point, just to make sure it works:

![Untitled-1](https://github.com/user-attachments/assets/84cfed61-dbd5-4987-a842-bc817a87fd7e)

**Comment by godreborn** [comment]
one last thing: OpenOrbis didn't add its ev like it said it would when installing from the exe, so I had to add it manually to the user section.  must be a bug of some sort, I guess.

**Comment by marcussacana** [comment]
Thanks for the details.
If you don't have PS4 jailbroken then you can't really test it but is possible to run the debug build on windows (but without audio), by making the GLTest build to works, just change to Debug_Win build and would work.

**Comment by godreborn** [comment]
> Thanks for the details. If you don't have PS4 jailbroken then you can't really test it but is possible to run the debug build on windows (but without audio), by making the GLTest build to works, just change to Debug_Win build and would work.

do you mean via debugging?  I got this error: 
![image](https://github.com/user-attachments/assets/925dbd5f-0bed-4aba-8e0f-9cc542a47b26)

with just GLTest.  it build it, but it wouldn't work via debugging.

**Comment by marcussacana** [comment]
You need copy those DLLs from your web browser, see 
https://github.com/marcussacana/FridayNightFunkin?tab=readme-ov-file#debugging

**Comment by godreborn** [comment]
> You need copy those DLLs from your web browser, see https://github.com/marcussacana/FridayNightFunkin?tab=readme-ov-file#debugging

I think that worked (didn't get an error), but I'm not sure what to do here: 
![image](https://github.com/user-attachments/assets/31e19c61-bbd5-4e55-aa10-3334e018ed52)

**Comment by marcussacana** [comment]
There are a lot of buttons in the interface right, click at "Game Test"
other buttons are made to debug other things
![image](https://github.com/user-attachments/assets/e35742a8-9acd-4d9c-9b59-4a7d1fa1b7ef)

**Comment by godreborn** [comment]
yeah, Game test does nothing.  none of the buttons do anything.  I've tried debugging the GLTest, and that's what happens.

**Comment by godreborn** [comment]
actually, the screen just flashed when I clicked on Game Test, but it did nothing.

**Comment by godreborn** [comment]
btw, if I keep it as class library, this happens: 
![image](https://github.com/user-attachments/assets/71976307-3e0b-4a07-9af3-4918e3e2c2a0)

I don't know if this is the cause of the problem or not.

**Comment by marcussacana** [comment]
You need the conditional build symbols to be set to works, check here

https://github.com/marcussacana/OrbisGL/blob/3f871971ffdc4c32d9b6739269d780f62830ce44/GLTest/GLTest.cs#L902-L931

Is possible to just remove the #if as well

**Comment by marcussacana** [comment]
After look a bit the code may be outdated, the game entrypoint changed a bit, should look like this
https://github.com/marcussacana/FridayNightFunkin/blob/22bebf35cd50e4e4ab8411d3a2da8515fa970ba6/main/main/Entrypoint.cs#L25-L32

but instead AddObject should be GLControl.GLApplication.AddObject

**Comment by marcussacana** [comment]
the final function code should be like this

```csharp
        private void button23_Click(object sender, EventArgs e)
        {
            FormBorderStyle = FormBorderStyle.None;
            Size = new Size(1920, 1080);

            WindowState = FormWindowState.Maximized;

            GLControl.SetSize(Size.Width, Size.Height);

            panel1.Visible = false;
            ILoadable main = new IntroScene(); 
            main.Load((i) => 
            { 
                 if (main.Loaded) 
                 { 
                     GLControl.GLApplication.AddObject(main); 
                 } 
            }); 
        }
```

**Comment by godreborn** [comment]
![image](https://github.com/user-attachments/assets/bcca56d9-e5b2-42e0-b6f1-84b92454f400)

**Comment by godreborn** [comment]
I was able to overcome that error by deleting the next two lines, but debugging still does nothing.

**Comment by marcussacana** [comment]
I can't see what lines from your screenshot

**Comment by godreborn** [comment]
> I can't see what lines from your screenshot

these few lines: 
![image](https://github.com/user-attachments/assets/ae96f83c-46e4-4aac-9646-17e0857ae06d)

**Comment by marcussacana** [comment]
I see, so when you click that button what happens, the window go fullscreen and keep black?

**Comment by godreborn** [comment]
it doesn't go black.  simply nothing happens.  sometimes the screen flickers when I press a button, but that's it.

**Comment by marcussacana** [comment]
Strange, a sec, I will check it on my side

**Comment by godreborn** [comment]
I could be messing up the coding.  I'm not a dev after all, so I'm just trying to follow instructions, when and where to put things that is.

**Comment by marcussacana** [comment]
if you don't mind, upload your build binaries from Debug_Win folder and send to me, I can analyze it here of what is wrong

**Comment by godreborn** [comment]
this?  https://www.mediafire.com/file/cvzfsy5wmfcuuv2/Debug_Win.zip/file

it's GLTest.  I've been trying to use it normally as well as debugging, and nothing.

**Comment by marcussacana** [comment]
It seems that your has the ORBIS symbol defined,  a moment

**Comment by marcussacana** [comment]
![image](https://github.com/user-attachments/assets/c094fcc2-7220-4065-88f2-3a84568d5d03)
Here, Debug_Win and X64 is selected?

**Comment by marcussacana** [comment]
You can look the project build settings like this
![image](https://github.com/user-attachments/assets/1f1f7035-4d51-4920-a98d-9e32c9f26c2c)
![image](https://github.com/user-attachments/assets/00e8e7fc-7579-4e4b-90aa-3c4797940fcc)
As you can see everting is at "Debug_Win"

If is, you can change the build symbols like this as well
![image](https://github.com/user-attachments/assets/1aa75324-4b7c-41d1-ade4-9e0848c4347e)

**Comment by marcussacana** [comment]
ORBIS is the Playstation 4 codename, if that is Set in the Step 5 of the last screenshot, the code will be targeted to the real PS4

**Comment by godreborn** [comment]
I changed it to ORBIS, and I got nothing selectable: 
![image](https://github.com/user-attachments/assets/aa6648da-9213-463d-a6bc-779885b98a0f)

**Comment by marcussacana** [comment]
Instead you should change out from ORBIS, the problem it has that your build included playstation code.

**Comment by godreborn** [comment]
nope, still doesn't work.  it flickers, then nothing.

**Comment by marcussacana** [comment]
Last try, find and replace in all files of the entire project
`#if ORBIS` to `#if false`
and
`#if !ORBIS` to `#if true`

**Comment by godreborn** [comment]
I tried starting over, but I got this error: error CS1061: 'Application' does not contain a definition for 'SwapBuffers' and no accessible extension method 'SwapBuffers' accepting a first argument of type 'Application' could be found (are you missing a using directive or an assembly reference?).  the biggest problem is I don't even know what this application is supposed to do, so I'm lost at trying to solve issues like this.  I just wanted to try building a ps4 app in windows.  I guess I just need someone to test the build/pkg more than anything else.

**Comment by marcussacana** [comment]
the error should be about this #if 
![image](https://github.com/user-attachments/assets/67c83d17-ede8-4710-aaa6-89e63d09d750)

Maybe OrbisGL build didn't updated the binaries, sometimes you need to open the OrbisGL project and build first manually, just after that build the game

**Comment by marcussacana** [comment]
Anyway if you want just see it working I can share a debug build

**Comment by marcussacana** [comment]
You just need open the "GLTest.exe", the main.exe does not works directly since is a entrypoint for PS4
[Dbg Win Build.zip](https://github.com/user-attachments/files/18267868/Dbg.Win.Build.zip)
Ohh, and the assets.zip that I shared in the readme must be in the same directory

**Comment by godreborn** [comment]
https://1fichier.com/?xv0yysx26g4bmqjc18pv

here's my build:

**Comment by marcussacana** [comment]
I will test in my ps4 soon

**Comment by godreborn** [comment]
thanks.  though, this gives me some comfort, but your debug version doesn't work for me either.  same issue.  it doesn't open anything.  I put assets.zip in the folder as well as assets/misc/assets.zip, and nothing.

**Comment by marcussacana** [comment]
I see, so it may have some OpenGL issue on your side, this build I tested here and it works.

**Comment by godreborn** [comment]
yeah, I updated my drivers for my gpu recently, because I had issues with ps4 obliteration on ubuntu 20.04.  I fixed it on ubuntu 22.04 iirc, so that could be the issue.  let me know if the pkg I uploaded works on your end.  it was too big for mediafire, but it was fine for 1fichier, which tends to delete stuff frequently, so make sure to get it soon.  thanks.

**Comment by godreborn** [comment]
and, by fixing it, I meant that I had vulkan issue on ubuntu 20.04, and it seemed unrelated to the drivers.  I had the same issue on ubuntu 22.04, but I was able to fix it through software installs iirc.  I don't think the same thing worked on ubuntu 20.04 though.

**Comment by marcussacana** [comment]
I will test the ps4 build soon, just waiting my vr headeset finish charging to me be able to turn on the playstation

**Comment by godreborn** [comment]
okay, thanks.  you've gone above and beyond what a lot of devs do.  I hope it works.

**Comment by marcussacana** [comment]
Nahh, I spent almost one year in this project, anyone interesed just make my spent time worth of it.

**Comment by godreborn** [comment]
> Nahh, I spent almost one year in this project, anyone interesed just make my spent time worth of it.

I would've thought the same thing.  it would've tickled me pink to know that someone else was interested in my project.

**Comment by godreborn** [comment]
not to say someone else wouldn't be.  I'm not sure how that came across.

**Comment by marcussacana** [comment]
Nahh, it's fine.
By the way, installing
![image](https://github.com/user-attachments/assets/a6c75796-1179-482f-aa34-b0a73ebb6195)

**Comment by marcussacana** [comment]
Yeah, your build works
![image](https://github.com/user-attachments/assets/6a5784d9-4942-4695-9d8b-5444e096da01)

**Comment by marcussacana** [comment]
![image](https://github.com/user-attachments/assets/34a48687-bf5b-4fdf-a376-7b9f56db7594)

**Comment by marcussacana** [comment]
So that's all, if you haven't anything more to ask you can close the issue :)

**Comment by godreborn** [comment]
Thanks so much.
